name: oc-new-p6-ci
run-name: ${{ github.actor }} a lancé le workflow CI/CD pour le projet oc-new-p6

on:
  push:
    branches: [ "main", "master", "feature/**", "hotfix/**" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
    test:
      name: exécute le script de tests unitaires sur toutes les applications
      runs-on: ubuntu-latest
      permissions:
        contents: read
        issues: read
        checks: write
        pull-requests: write
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Run tests
          run: chmod +x run-tests.sh && ./run-tests.sh
        - name: Upload test results
          uses: actions/upload-artifact@v4
          if: always() # Toujours exécuter même si les tests échouent
          with:
            name: test-results
            path: test-results/
        - name: Publish Test Results
          uses: EnricoMi/publish-unit-test-result-action@v2
          if: always() # Toujours exécuter même si les tests échouent
          with:
            files: "test-results/*.xml"
